Repository ucsb-cs156-s24/proj-courses-s24-4pm-4, pull requests merged in 2024-05, with the labels that each got.

#28 Add PersonalSections Controller Delete and Tests
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsControllerTests.java
Labels: 10, Marge Candidate

#36 H2 Console Option
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: 5

#37 Updated Web Application Title
  frontend/public/index.html
Labels: 5, FIXME-Respond to CR

#24 Remove Courses Page Feature
  frontend/src/App.js
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Courses/PSCourseCreatePage.js
  frontend/src/main/pages/Courses/PSCourseIndexPage.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
Labels: HOLD-Waiting on another PR to merge

#38 Added Improvement Course History Search Feature
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeSearchForm.js
  frontend/src/tests/components/BasicCourseSearch/CourseOverTimeSearchForm.test.js
Labels: 10
